/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-error-container": "#93000a",
        "primary-fixed": "#d2e4ff",
        "surface-variant": "#d3e4fe",
        "primary": "#00355f",
        "inverse-surface": "#213145",
        "surface-gray": "#F8FAFC",
        "on-secondary-container": "#684000",
        "border-subtle": "#E2E8F0",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        "surface-container-low": "#eff4ff",
        "secondary-fixed-dim": "#ffb95f",
        "tertiary-container": "#005539",
        "success-teal": "#10B981",
        "on-tertiary-fixed-variant": "#005236",
        "background": "#f8f9ff",
        "trust-navy": "#0F4C81",
        "on-tertiary-fixed": "#002113",
        "secondary-fixed": "#ffddb8",
        "on-primary-container": "#8ebdf9",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed-variant": "#07497d",
        "error-red": "#EF4444",
        "surface-tint": "#2d6197",
        "secondary": "#855300",
        "on-secondary": "#ffffff",
        "outline-variant": "#c2c7d1",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#a0c9ff",
        "tertiary-fixed": "#6ffbbe",
        "inverse-on-surface": "#eaf1ff",
        "primary-container": "#0f4c81",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "secondary-container": "#fea619",
        "surface-container-lowest": "#ffffff",
        "electric-blue": "#3B82F6",
        "error": "#ba1a1a",
        "surface-container": "#e5eeff",
        "outline": "#727780",
        "inverse-primary": "#a0c9ff",
        "error-container": "#ffdad6",
        "on-surface": "#0b1c30",
        "on-tertiary-container": "#3dd197",
        "action-amber": "#F59E0B",
        "on-error": "#ffffff",
        "tertiary": "#003c27",
        "on-primary-fixed": "#001c37",
        "surface-container-high": "#dce9ff",
        "on-surface-variant": "#42474f",
        "on-background": "#0b1c30"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "title-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "technical-data": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      "spacing": {
        "gutter": "24px",
        "base": "4px",
        "md": "16px",
        "lg": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "xl": "32px",
        "xs": "4px",
        "3xl": "64px",
        "2xl": "48px",
        "sm": "8px"
      },
      "fontSize": {
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "technical-data": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
